//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import RswiftResources
import UIKit

private class BundleFinder {}
let R = _R(bundle: Bundle(for: BundleFinder.self))

struct _R {
  let bundle: Foundation.Bundle

  let entitlements = entitlements()

  var image: image { .init(bundle: bundle) }
  var font: font { .init(bundle: bundle) }
  var file: file { .init(bundle: bundle) }
  var storyboard: storyboard { .init(bundle: bundle) }

  func image(bundle: Foundation.Bundle) -> image {
    .init(bundle: bundle)
  }
  func font(bundle: Foundation.Bundle) -> font {
    .init(bundle: bundle)
  }
  func file(bundle: Foundation.Bundle) -> file {
    .init(bundle: bundle)
  }
  func storyboard(bundle: Foundation.Bundle) -> storyboard {
    .init(bundle: bundle)
  }
  func validate() throws {
    try self.font.validate()
    try self.storyboard.validate()
  }

  struct project {
    let developmentRegion = "en"
  }

  /// This `_R.image` struct is generated, and contains static references to 97 images.
  struct image {
    let bundle: Foundation.Bundle

    /// Image `Frame 492`.
    var frame492: RswiftResources.ImageResource { .init(name: "Frame 492", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `LaunchImage`.
    var launchImage: RswiftResources.ImageResource { .init(name: "LaunchImage", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Vector`.
    var vector: RswiftResources.ImageResource { .init(name: "Vector", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `animal`.
    var animal: RswiftResources.ImageResource { .init(name: "animal", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `animal1`.
    var animal1: RswiftResources.ImageResource { .init(name: "animal1", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `animal2`.
    var animal2: RswiftResources.ImageResource { .init(name: "animal2", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `animal3`.
    var animal3: RswiftResources.ImageResource { .init(name: "animal3", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `animal4`.
    var animal4: RswiftResources.ImageResource { .init(name: "animal4", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `app_icon_1`.
    var app_icon_1: RswiftResources.ImageResource { .init(name: "app_icon_1", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `app_icon_2`.
    var app_icon_2: RswiftResources.ImageResource { .init(name: "app_icon_2", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `app_icon_3`.
    var app_icon_3: RswiftResources.ImageResource { .init(name: "app_icon_3", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `app_icon_4`.
    var app_icon_4: RswiftResources.ImageResource { .init(name: "app_icon_4", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `app_icon_5`.
    var app_icon_5: RswiftResources.ImageResource { .init(name: "app_icon_5", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `app_icon_6`.
    var app_icon_6: RswiftResources.ImageResource { .init(name: "app_icon_6", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `app_icon_7`.
    var app_icon_7: RswiftResources.ImageResource { .init(name: "app_icon_7", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `app_icon_8`.
    var app_icon_8: RswiftResources.ImageResource { .init(name: "app_icon_8", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `background-main`.
    var backgroundMain: RswiftResources.ImageResource { .init(name: "background-main", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `background_DS_1`.
    var background_DS_1: RswiftResources.ImageResource { .init(name: "background_DS_1", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `background_bo1`.
    var background_bo1: RswiftResources.ImageResource { .init(name: "background_bo1", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `banner_time`.
    var banner_time: RswiftResources.ImageResource { .init(name: "banner_time", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `button_clear_text`.
    var button_clear_text: RswiftResources.ImageResource { .init(name: "button_clear_text", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `button_copy_text`.
    var button_copy_text: RswiftResources.ImageResource { .init(name: "button_copy_text", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `car1`.
    var car1: RswiftResources.ImageResource { .init(name: "car1", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `car2`.
    var car2: RswiftResources.ImageResource { .init(name: "car2", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `car3`.
    var car3: RswiftResources.ImageResource { .init(name: "car3", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `car4`.
    var car4: RswiftResources.ImageResource { .init(name: "car4", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `car5`.
    var car5: RswiftResources.ImageResource { .init(name: "car5", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon-heart`.
    var iconHeart: RswiftResources.ImageResource { .init(name: "icon-heart", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon-red-heart`.
    var iconRedHeart: RswiftResources.ImageResource { .init(name: "icon-red-heart", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon-refresh`.
    var iconRefresh: RswiftResources.ImageResource { .init(name: "icon-refresh", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon-refresh 1`.
    var iconRefresh1: RswiftResources.ImageResource { .init(name: "icon-refresh 1", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_antonym`.
    var icon_antonym: RswiftResources.ImageResource { .init(name: "icon_antonym", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_arrow_down`.
    var icon_arrow_down: RswiftResources.ImageResource { .init(name: "icon_arrow_down", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_back`.
    var icon_back: RswiftResources.ImageResource { .init(name: "icon_back", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_best_seller`.
    var icon_best_seller: RswiftResources.ImageResource { .init(name: "icon_best_seller", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_camera`.
    var icon_camera: RswiftResources.ImageResource { .init(name: "icon_camera", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_change_tone`.
    var icon_change_tone: RswiftResources.ImageResource { .init(name: "icon_change_tone", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_close`.
    var icon_close: RswiftResources.ImageResource { .init(name: "icon_close", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_commit_1`.
    var icon_commit_1: RswiftResources.ImageResource { .init(name: "icon_commit_1", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_commit_2`.
    var icon_commit_2: RswiftResources.ImageResource { .init(name: "icon_commit_2", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_commit_3`.
    var icon_commit_3: RswiftResources.ImageResource { .init(name: "icon_commit_3", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_commit_4`.
    var icon_commit_4: RswiftResources.ImageResource { .init(name: "icon_commit_4", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_continue`.
    var icon_continue: RswiftResources.ImageResource { .init(name: "icon_continue", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_copy`.
    var icon_copy: RswiftResources.ImageResource { .init(name: "icon_copy", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_define`.
    var icon_define: RswiftResources.ImageResource { .init(name: "icon_define", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_discard`.
    var icon_discard: RswiftResources.ImageResource { .init(name: "icon_discard", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_done_keyboard`.
    var icon_done_keyboard: RswiftResources.ImageResource { .init(name: "icon_done_keyboard", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_down`.
    var icon_down: RswiftResources.ImageResource { .init(name: "icon_down", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_feature_antonym`.
    var icon_feature_antonym: RswiftResources.ImageResource { .init(name: "icon_feature_antonym", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_feature_change_tone`.
    var icon_feature_change_tone: RswiftResources.ImageResource { .init(name: "icon_feature_change_tone", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_feature_define`.
    var icon_feature_define: RswiftResources.ImageResource { .init(name: "icon_feature_define", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_feature_fix_grammar`.
    var icon_feature_fix_grammar: RswiftResources.ImageResource { .init(name: "icon_feature_fix_grammar", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_feature_improve`.
    var icon_feature_improve: RswiftResources.ImageResource { .init(name: "icon_feature_improve", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_feature_make_longer`.
    var icon_feature_make_longer: RswiftResources.ImageResource { .init(name: "icon_feature_make_longer", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_feature_make_shorter`.
    var icon_feature_make_shorter: RswiftResources.ImageResource { .init(name: "icon_feature_make_shorter", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_feature_synonym`.
    var icon_feature_synonym: RswiftResources.ImageResource { .init(name: "icon_feature_synonym", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_feature_translate`.
    var icon_feature_translate: RswiftResources.ImageResource { .init(name: "icon_feature_translate", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_fix_grammar`.
    var icon_fix_grammar: RswiftResources.ImageResource { .init(name: "icon_fix_grammar", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_gallery`.
    var icon_gallery: RswiftResources.ImageResource { .init(name: "icon_gallery", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_highlight_ds`.
    var icon_highlight_ds: RswiftResources.ImageResource { .init(name: "icon_highlight_ds", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_king`.
    var icon_king: RswiftResources.ImageResource { .init(name: "icon_king", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_left`.
    var icon_left: RswiftResources.ImageResource { .init(name: "icon_left", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_menu`.
    var icon_menu: RswiftResources.ImageResource { .init(name: "icon_menu", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_refresh`.
    var icon_refresh: RswiftResources.ImageResource { .init(name: "icon_refresh", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_secured`.
    var icon_secured: RswiftResources.ImageResource { .init(name: "icon_secured", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `image_categories`.
    var image_categories: RswiftResources.ImageResource { .init(name: "image_categories", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `landscape`.
    var landscape: RswiftResources.ImageResource { .init(name: "landscape", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `launch1`.
    var launch1: RswiftResources.ImageResource { .init(name: "launch1", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `launch2`.
    var launch2: RswiftResources.ImageResource { .init(name: "launch2", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `launch3`.
    var launch3: RswiftResources.ImageResource { .init(name: "launch3", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `launch4`.
    var launch4: RswiftResources.ImageResource { .init(name: "launch4", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `launch5`.
    var launch5: RswiftResources.ImageResource { .init(name: "launch5", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `man`.
    var man: RswiftResources.ImageResource { .init(name: "man", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `man1`.
    var man1: RswiftResources.ImageResource { .init(name: "man1", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `man2`.
    var man2: RswiftResources.ImageResource { .init(name: "man2", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `man3`.
    var man3: RswiftResources.ImageResource { .init(name: "man3", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `man4`.
    var man4: RswiftResources.ImageResource { .init(name: "man4", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `man5`.
    var man5: RswiftResources.ImageResource { .init(name: "man5", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `man6`.
    var man6: RswiftResources.ImageResource { .init(name: "man6", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `mecha_robot`.
    var mecha_robot: RswiftResources.ImageResource { .init(name: "mecha_robot", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `robot1`.
    var robot1: RswiftResources.ImageResource { .init(name: "robot1", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `robot2`.
    var robot2: RswiftResources.ImageResource { .init(name: "robot2", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `robot3`.
    var robot3: RswiftResources.ImageResource { .init(name: "robot3", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `robot4`.
    var robot4: RswiftResources.ImageResource { .init(name: "robot4", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `robot5`.
    var robot5: RswiftResources.ImageResource { .init(name: "robot5", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `robot6`.
    var robot6: RswiftResources.ImageResource { .init(name: "robot6", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `splash`.
    var splash: RswiftResources.ImageResource { .init(name: "splash", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `supper_car`.
    var supper_car: RswiftResources.ImageResource { .init(name: "supper_car", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `surrealistic_wallpaper_21_origin 1`.
    var surrealistic_wallpaper_21_origin1: RswiftResources.ImageResource { .init(name: "surrealistic_wallpaper_21_origin 1", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `tabbar_back`.
    var tabbar_back: RswiftResources.ImageResource { .init(name: "tabbar_back", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `tabbar_setting_dark`.
    var tabbar_setting_dark: RswiftResources.ImageResource { .init(name: "tabbar_setting_dark", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `woman`.
    var woman: RswiftResources.ImageResource { .init(name: "woman", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `woman1`.
    var woman1: RswiftResources.ImageResource { .init(name: "woman1", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `woman2`.
    var woman2: RswiftResources.ImageResource { .init(name: "woman2", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `woman3`.
    var woman3: RswiftResources.ImageResource { .init(name: "woman3", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `woman5`.
    var woman5: RswiftResources.ImageResource { .init(name: "woman5", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `woman6`.
    var woman6: RswiftResources.ImageResource { .init(name: "woman6", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
  }

  /// This `_R.entitlements` struct is generated, and contains static references to 0 properties.
  struct entitlements {
    let comAppleSecurityAppSandbox: Bool = true
    let comAppleSecurityNetworkClient: Bool = true
  }

  /// This `_R.font` struct is generated, and contains static references to 7 fonts.
  struct font: Sequence {
    let bundle: Foundation.Bundle

    /// Font `OpenSans-Regular`.
    var openSansRegular: RswiftResources.FontResource { .init(name: "OpenSans-Regular", bundle: bundle, filename: "OpenSans-Text.ttf") }

    /// Font `OpenSans-SemiBold`.
    var openSansSemiBold: RswiftResources.FontResource { .init(name: "OpenSans-SemiBold", bundle: bundle, filename: "OpenSans-SemiBold.ttf") }

    /// Font `SFProText-Bold`.
    var sfProTextBold: RswiftResources.FontResource { .init(name: "SFProText-Bold", bundle: bundle, filename: "SF-Pro-Text-Bold.ttf") }

    /// Font `SFProText-Heavy`.
    var sfProTextHeavy: RswiftResources.FontResource { .init(name: "SFProText-Heavy", bundle: bundle, filename: "SF-Pro-Text-Heavy.ttf") }

    /// Font `SFProText-Medium`.
    var sfProTextMedium: RswiftResources.FontResource { .init(name: "SFProText-Medium", bundle: bundle, filename: "SF-Pro-Text-Medium.ttf") }

    /// Font `SFProText-Regular`.
    var sfProTextRegular: RswiftResources.FontResource { .init(name: "SFProText-Regular", bundle: bundle, filename: "SF-Pro-Text-Regular.ttf") }

    /// Font `SFProText-Semibold`.
    var sfProTextSemibold: RswiftResources.FontResource { .init(name: "SFProText-Semibold", bundle: bundle, filename: "SF-Pro-Text-Semibold.ttf") }

    func makeIterator() -> IndexingIterator<[RswiftResources.FontResource]> {
      [openSansRegular, openSansSemiBold, sfProTextBold, sfProTextHeavy, sfProTextMedium, sfProTextRegular, sfProTextSemibold].makeIterator()
    }
    func validate() throws {
      for font in self {
        if !font.canBeLoaded() { throw RswiftResources.ValidationError("[R.swift] Font '\(font.name)' could not be loaded, is '\(font.filename)' added to the UIAppFonts array in this targets Info.plist?") }
      }
    }
  }

  /// This `_R.file` struct is generated, and contains static references to 9 resource files.
  struct file {
    let bundle: Foundation.Bundle

    /// Resource file `GoogleService-Info.plist`.
    var googleServiceInfoPlist: RswiftResources.FileResource { .init(name: "GoogleService-Info", pathExtension: "plist", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `OpenSans-SemiBold.ttf`.
    var openSansSemiBoldTtf: RswiftResources.FileResource { .init(name: "OpenSans-SemiBold", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `OpenSans-Text.ttf`.
    var openSansTextTtf: RswiftResources.FileResource { .init(name: "OpenSans-Text", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Plist`.
    var plist: RswiftResources.FileResource { .init(name: "Plist", pathExtension: "", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `SF-Pro-Text-Bold.ttf`.
    var sfProTextBoldTtf: RswiftResources.FileResource { .init(name: "SF-Pro-Text-Bold", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `SF-Pro-Text-Heavy.ttf`.
    var sfProTextHeavyTtf: RswiftResources.FileResource { .init(name: "SF-Pro-Text-Heavy", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `SF-Pro-Text-Medium.ttf`.
    var sfProTextMediumTtf: RswiftResources.FileResource { .init(name: "SF-Pro-Text-Medium", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `SF-Pro-Text-Regular.ttf`.
    var sfProTextRegularTtf: RswiftResources.FileResource { .init(name: "SF-Pro-Text-Regular", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `SF-Pro-Text-Semibold.ttf`.
    var sfProTextSemiboldTtf: RswiftResources.FileResource { .init(name: "SF-Pro-Text-Semibold", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }
  }

  /// This `_R.storyboard` struct is generated, and contains static references to 1 storyboards.
  struct storyboard {
    let bundle: Foundation.Bundle
    var main: main { .init(bundle: bundle) }

    func main(bundle: Foundation.Bundle) -> main {
      .init(bundle: bundle)
    }
    func validate() throws {
      try self.main.validate()
    }


    /// Storyboard `Main`.
    struct main: RswiftResources.StoryboardReference {
      let bundle: Foundation.Bundle

      let name = "Main"
      func validate() throws {

      }
    }
  }
}